services:
  - type: cron
    name: daily-digest-job
    env: docker
    dockerfilePath: ./Dockerfile
    schedule: "0 0 * * *"
    dockerCommand: python main.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: MY_EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false

